name: CI

on:
  push:
    branches: [ main ]

env:
  # full image reference
  IMAGE: ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/autobot-futures:latest

jobs:
  lint-and-test:
    name: 🐍 Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: pytest -q

  build-and-push:
    name: 🐋 Build & Push Docker Image
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build & push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          load: true      # leaves the image in runner's Docker daemon
          tags: ${{ env.IMAGE }}

  deploy:
    name: 🚀 Deploy to a local Kind cluster
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install kubectl & kind
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -Lo kubectl https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.21.0/kind-linux-amd64
          chmod +x kind && sudo mv kind /usr/local/bin/

      - name: Create kind cluster
        run: kind create cluster --name ci

      - name: Pull image from registry
        run: docker pull ${{ env.IMAGE }}

      - name: Load image into kind
        run: kind load docker-image ${{ env.IMAGE }} --name ci

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f infra/k8s/deployment.yaml
          kubectl apply -f infra/k8s/service.yaml
      - name: Show all resources
        run: kubectl get all --namespace default

      - name: Tear down Kind
        if: always()
        run: kind delete cluster --name ci
